image: mono:latest

before_script:
    - nuget restore -NonInteractive

build:
    artifacts:
        paths:
            - /*
        untracked: false
        expire_in: 30 days
    script:
    - msbuild  "ETEInterface.sln" /property:Configuration=Release
    - ls